
#include "Meta_Maps.h"

#include <vkbinding/vk/bitfield.h>


using namespace vk;


namespace vkbinding { namespace aux
{


const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_0{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_A =
{
    { "VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV) },
    { "VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_NV", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_NV) },
    { "VK_ACCESS_COLOR_ATTACHMENT_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_COLOR_ATTACHMENT_READ_BIT) },
    { "VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT) },
    { "VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT) },
    { "VK_ACCESS_COMMAND_PROCESS_READ_BIT_NVX", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_COMMAND_PROCESS_READ_BIT_NVX) },
    { "VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX) },
    { "VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT) },
    { "VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT) },
    { "VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT) },
    { "VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT) },
    { "VK_ACCESS_HOST_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_HOST_READ_BIT) },
    { "VK_ACCESS_HOST_WRITE_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_HOST_WRITE_BIT) },
    { "VK_ACCESS_INDEX_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_INDEX_READ_BIT) },
    { "VK_ACCESS_INDIRECT_COMMAND_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_INDIRECT_COMMAND_READ_BIT) },
    { "VK_ACCESS_INPUT_ATTACHMENT_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_INPUT_ATTACHMENT_READ_BIT) },
    { "VK_ACCESS_MEMORY_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_MEMORY_READ_BIT) },
    { "VK_ACCESS_MEMORY_WRITE_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_MEMORY_WRITE_BIT) },
    { "VK_ACCESS_RESERVED_28_BIT_KHR", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_RESERVED_28_BIT_KHR) },
    { "VK_ACCESS_RESERVED_29_BIT_KHR", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_RESERVED_29_BIT_KHR) },
    { "VK_ACCESS_RESERVED_30_BIT_KHR", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_RESERVED_30_BIT_KHR) },
    { "VK_ACCESS_RESERVED_31_BIT_KHR", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_RESERVED_31_BIT_KHR) },
    { "VK_ACCESS_SHADER_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_SHADER_READ_BIT) },
    { "VK_ACCESS_SHADER_WRITE_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_SHADER_WRITE_BIT) },
    { "VK_ACCESS_SHADING_RATE_IMAGE_READ_BIT_NV", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_SHADING_RATE_IMAGE_READ_BIT_NV) },
    { "VK_ACCESS_TRANSFER_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_TRANSFER_READ_BIT) },
    { "VK_ACCESS_TRANSFER_WRITE_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_TRANSFER_WRITE_BIT) },
    { "VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT) },
    { "VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT) },
    { "VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT) },
    { "VK_ACCESS_UNIFORM_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_UNIFORM_READ_BIT) },
    { "VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT", static_cast<VKbitfield>(VkAccessFlagBits::VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT) },
    { "VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT", static_cast<VKbitfield>(VkAttachmentDescriptionFlagBits::VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_B =
{
    { "VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT", static_cast<VKbitfield>(VkBufferCreateFlagBits::VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT) },
    { "VK_BUFFER_CREATE_PROTECTED_BIT", static_cast<VKbitfield>(VkBufferCreateFlagBits::VK_BUFFER_CREATE_PROTECTED_BIT) },
    { "VK_BUFFER_CREATE_SPARSE_ALIASED_BIT", static_cast<VKbitfield>(VkBufferCreateFlagBits::VK_BUFFER_CREATE_SPARSE_ALIASED_BIT) },
    { "VK_BUFFER_CREATE_SPARSE_BINDING_BIT", static_cast<VKbitfield>(VkBufferCreateFlagBits::VK_BUFFER_CREATE_SPARSE_BINDING_BIT) },
    { "VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT", static_cast<VKbitfield>(VkBufferCreateFlagBits::VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT) },
    { "VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT) },
    { "VK_BUFFER_USAGE_INDEX_BUFFER_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_INDEX_BUFFER_BIT) },
    { "VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT) },
    { "VK_BUFFER_USAGE_RAY_TRACING_BIT_NV", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_RAY_TRACING_BIT_NV) },
    { "VK_BUFFER_USAGE_RESERVED_13_BIT_KHR", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_RESERVED_13_BIT_KHR) },
    { "VK_BUFFER_USAGE_RESERVED_14_BIT_KHR", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_RESERVED_14_BIT_KHR) },
    { "VK_BUFFER_USAGE_RESERVED_15_BIT_KHR", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_RESERVED_15_BIT_KHR) },
    { "VK_BUFFER_USAGE_RESERVED_16_BIT_KHR", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_RESERVED_16_BIT_KHR) },
    { "VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_EXT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_EXT) },
    { "VK_BUFFER_USAGE_STORAGE_BUFFER_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_STORAGE_BUFFER_BIT) },
    { "VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT) },
    { "VK_BUFFER_USAGE_TRANSFER_DST_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_TRANSFER_DST_BIT) },
    { "VK_BUFFER_USAGE_TRANSFER_SRC_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_TRANSFER_SRC_BIT) },
    { "VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT) },
    { "VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT) },
    { "VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT) },
    { "VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT) },
    { "VK_BUFFER_USAGE_VERTEX_BUFFER_BIT", static_cast<VKbitfield>(VkBufferUsageFlagBits::VK_BUFFER_USAGE_VERTEX_BUFFER_BIT) },
    { "VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV", static_cast<VKbitfield>(VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV) },
    { "VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV", static_cast<VKbitfield>(VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV) },
    { "VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV", static_cast<VKbitfield>(VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV) },
    { "VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV", static_cast<VKbitfield>(VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV) },
    { "VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV", static_cast<VKbitfield>(VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_C =
{
    { "VK_COLOR_COMPONENT_A_BIT", static_cast<VKbitfield>(VkColorComponentFlagBits::VK_COLOR_COMPONENT_A_BIT) },
    { "VK_COLOR_COMPONENT_B_BIT", static_cast<VKbitfield>(VkColorComponentFlagBits::VK_COLOR_COMPONENT_B_BIT) },
    { "VK_COLOR_COMPONENT_G_BIT", static_cast<VKbitfield>(VkColorComponentFlagBits::VK_COLOR_COMPONENT_G_BIT) },
    { "VK_COLOR_COMPONENT_R_BIT", static_cast<VKbitfield>(VkColorComponentFlagBits::VK_COLOR_COMPONENT_R_BIT) },
    { "VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT", static_cast<VKbitfield>(VkCommandBufferResetFlagBits::VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT) },
    { "VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT", static_cast<VKbitfield>(VkCommandBufferUsageFlagBits::VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT) },
    { "VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT", static_cast<VKbitfield>(VkCommandBufferUsageFlagBits::VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT) },
    { "VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT", static_cast<VKbitfield>(VkCommandBufferUsageFlagBits::VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT) },
    { "VK_COMMAND_POOL_CREATE_PROTECTED_BIT", static_cast<VKbitfield>(VkCommandPoolCreateFlagBits::VK_COMMAND_POOL_CREATE_PROTECTED_BIT) },
    { "VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT", static_cast<VKbitfield>(VkCommandPoolCreateFlagBits::VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT) },
    { "VK_COMMAND_POOL_CREATE_TRANSIENT_BIT", static_cast<VKbitfield>(VkCommandPoolCreateFlagBits::VK_COMMAND_POOL_CREATE_TRANSIENT_BIT) },
    { "VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT", static_cast<VKbitfield>(VkCommandPoolResetFlagBits::VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT) },
    { "VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR", static_cast<VKbitfield>(VkCompositeAlphaFlagBitsKHR::VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR) },
    { "VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR", static_cast<VKbitfield>(VkCompositeAlphaFlagBitsKHR::VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR) },
    { "VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR", static_cast<VKbitfield>(VkCompositeAlphaFlagBitsKHR::VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR) },
    { "VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR", static_cast<VKbitfield>(VkCompositeAlphaFlagBitsKHR::VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR) },
    { "VK_CONDITIONAL_RENDERING_INVERTED_BIT_EXT", static_cast<VKbitfield>(VkConditionalRenderingFlagBitsEXT::VK_CONDITIONAL_RENDERING_INVERTED_BIT_EXT) },
    { "VK_CULL_MODE_BACK_BIT", static_cast<VKbitfield>(VkCullModeFlagBits::VK_CULL_MODE_BACK_BIT) },
    { "VK_CULL_MODE_FRONT_AND_BACK", static_cast<VKbitfield>(VkCullModeFlagBits::VK_CULL_MODE_FRONT_AND_BACK) },
    { "VK_CULL_MODE_FRONT_BIT", static_cast<VKbitfield>(VkCullModeFlagBits::VK_CULL_MODE_FRONT_BIT) },
    { "VK_CULL_MODE_NONE", static_cast<VKbitfield>(VkCullModeFlagBits::VK_CULL_MODE_NONE) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_D =
{
    { "VK_DEBUG_REPORT_DEBUG_BIT_EXT", static_cast<VKbitfield>(VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_DEBUG_BIT_EXT) },
    { "VK_DEBUG_REPORT_ERROR_BIT_EXT", static_cast<VKbitfield>(VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_ERROR_BIT_EXT) },
    { "VK_DEBUG_REPORT_INFORMATION_BIT_EXT", static_cast<VKbitfield>(VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_INFORMATION_BIT_EXT) },
    { "VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT", static_cast<VKbitfield>(VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT) },
    { "VK_DEBUG_REPORT_WARNING_BIT_EXT", static_cast<VKbitfield>(VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_WARNING_BIT_EXT) },
    { "VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT", static_cast<VKbitfield>(VkDebugUtilsMessageSeverityFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT) },
    { "VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT", static_cast<VKbitfield>(VkDebugUtilsMessageSeverityFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT) },
    { "VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT", static_cast<VKbitfield>(VkDebugUtilsMessageSeverityFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT) },
    { "VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT", static_cast<VKbitfield>(VkDebugUtilsMessageSeverityFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT) },
    { "VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT", static_cast<VKbitfield>(VkDebugUtilsMessageTypeFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT) },
    { "VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT", static_cast<VKbitfield>(VkDebugUtilsMessageTypeFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT) },
    { "VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT", static_cast<VKbitfield>(VkDebugUtilsMessageTypeFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT) },
    { "VK_DEPENDENCY_BY_REGION_BIT", static_cast<VKbitfield>(VkDependencyFlagBits::VK_DEPENDENCY_BY_REGION_BIT) },
    { "VK_DEPENDENCY_DEVICE_GROUP_BIT", static_cast<VKbitfield>(VkDependencyFlagBits::VK_DEPENDENCY_DEVICE_GROUP_BIT) },
    { "VK_DEPENDENCY_DEVICE_GROUP_BIT_KHR", static_cast<VKbitfield>(VkDependencyFlagBits::VK_DEPENDENCY_DEVICE_GROUP_BIT_KHR) },
    { "VK_DEPENDENCY_VIEW_LOCAL_BIT", static_cast<VKbitfield>(VkDependencyFlagBits::VK_DEPENDENCY_VIEW_LOCAL_BIT) },
    { "VK_DEPENDENCY_VIEW_LOCAL_BIT_KHR", static_cast<VKbitfield>(VkDependencyFlagBits::VK_DEPENDENCY_VIEW_LOCAL_BIT_KHR) },
    { "VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT", static_cast<VKbitfield>(VkDescriptorBindingFlagBitsEXT::VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT) },
    { "VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT", static_cast<VKbitfield>(VkDescriptorBindingFlagBitsEXT::VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT) },
    { "VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT", static_cast<VKbitfield>(VkDescriptorBindingFlagBitsEXT::VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT) },
    { "VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT", static_cast<VKbitfield>(VkDescriptorBindingFlagBitsEXT::VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT) },
    { "VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT", static_cast<VKbitfield>(VkDescriptorPoolCreateFlagBits::VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT) },
    { "VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT_EXT", static_cast<VKbitfield>(VkDescriptorPoolCreateFlagBits::VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT_EXT) },
    { "VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR", static_cast<VKbitfield>(VkDescriptorSetLayoutCreateFlagBits::VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR) },
    { "VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT", static_cast<VKbitfield>(VkDescriptorSetLayoutCreateFlagBits::VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT) },
    { "VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR", static_cast<VKbitfield>(VkDeviceGroupPresentModeFlagBitsKHR::VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR) },
    { "VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR", static_cast<VKbitfield>(VkDeviceGroupPresentModeFlagBitsKHR::VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR) },
    { "VK_DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR", static_cast<VKbitfield>(VkDeviceGroupPresentModeFlagBitsKHR::VK_DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR) },
    { "VK_DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR", static_cast<VKbitfield>(VkDeviceGroupPresentModeFlagBitsKHR::VK_DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR) },
    { "VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT", static_cast<VKbitfield>(VkDeviceQueueCreateFlagBits::VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT) },
    { "VK_DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR", static_cast<VKbitfield>(VkDisplayPlaneAlphaFlagBitsKHR::VK_DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR) },
    { "VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR", static_cast<VKbitfield>(VkDisplayPlaneAlphaFlagBitsKHR::VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR) },
    { "VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR", static_cast<VKbitfield>(VkDisplayPlaneAlphaFlagBitsKHR::VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR) },
    { "VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR", static_cast<VKbitfield>(VkDisplayPlaneAlphaFlagBitsKHR::VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_E =
{
    { "VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT", static_cast<VKbitfield>(VkExternalFenceFeatureFlagBits::VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT) },
    { "VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT_KHR", static_cast<VKbitfield>(VkExternalFenceFeatureFlagBits::VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT_KHR) },
    { "VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT", static_cast<VKbitfield>(VkExternalFenceFeatureFlagBits::VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT) },
    { "VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT_KHR", static_cast<VKbitfield>(VkExternalFenceFeatureFlagBits::VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT_KHR) },
    { "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT", static_cast<VKbitfield>(VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT) },
    { "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR", static_cast<VKbitfield>(VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR) },
    { "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT", static_cast<VKbitfield>(VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT) },
    { "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR", static_cast<VKbitfield>(VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR) },
    { "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT", static_cast<VKbitfield>(VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT) },
    { "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR", static_cast<VKbitfield>(VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR) },
    { "VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT", static_cast<VKbitfield>(VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT) },
    { "VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT_KHR", static_cast<VKbitfield>(VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT) },
    { "VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_NV", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBitsNV::VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_NV) },
    { "VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT) },
    { "VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_NV", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBitsNV::VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_NV) },
    { "VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT) },
    { "VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_NV", static_cast<VKbitfield>(VkExternalMemoryFeatureFlagBitsNV::VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_NV) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_BIT_NV", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBitsNV::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_BIT_NV) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_KMT_BIT_NV", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBitsNV::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_KMT_BIT_NV) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_MAPPED_FOREIGN_MEMORY_BIT_EXT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_MAPPED_FOREIGN_MEMORY_BIT_EXT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_NV", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBitsNV::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_NV) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR) },
    { "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_NV", static_cast<VKbitfield>(VkExternalMemoryHandleTypeFlagBitsNV::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_NV) },
    { "VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT", static_cast<VKbitfield>(VkExternalSemaphoreFeatureFlagBits::VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT) },
    { "VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT_KHR", static_cast<VKbitfield>(VkExternalSemaphoreFeatureFlagBits::VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT_KHR) },
    { "VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT", static_cast<VKbitfield>(VkExternalSemaphoreFeatureFlagBits::VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT) },
    { "VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT_KHR", static_cast<VKbitfield>(VkExternalSemaphoreFeatureFlagBits::VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT_KHR) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT_KHR", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT_KHR) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT) },
    { "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT_KHR", static_cast<VKbitfield>(VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT_KHR) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_F =
{
    { "VK_FENCE_CREATE_SIGNALED_BIT", static_cast<VKbitfield>(VkFenceCreateFlagBits::VK_FENCE_CREATE_SIGNALED_BIT) },
    { "VK_FENCE_IMPORT_TEMPORARY_BIT", static_cast<VKbitfield>(VkFenceImportFlagBits::VK_FENCE_IMPORT_TEMPORARY_BIT) },
    { "VK_FENCE_IMPORT_TEMPORARY_BIT_KHR", static_cast<VKbitfield>(VkFenceImportFlagBits::VK_FENCE_IMPORT_TEMPORARY_BIT_KHR) },
    { "VK_FORMAT_FEATURE_BLIT_DST_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_BLIT_DST_BIT) },
    { "VK_FORMAT_FEATURE_BLIT_SRC_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_BLIT_SRC_BIT) },
    { "VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT) },
    { "VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT) },
    { "VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT) },
    { "VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR) },
    { "VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT) },
    { "VK_FORMAT_FEATURE_DISJOINT_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_DISJOINT_BIT) },
    { "VK_FORMAT_FEATURE_DISJOINT_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_DISJOINT_BIT_KHR) },
    { "VK_FORMAT_FEATURE_FRAGMENT_DENSITY_MAP_BIT_EXT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_FRAGMENT_DENSITY_MAP_BIT_EXT) },
    { "VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT) },
    { "VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR) },
    { "VK_FORMAT_FEATURE_RESERVED_25_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_RESERVED_25_BIT_KHR) },
    { "VK_FORMAT_FEATURE_RESERVED_26_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_RESERVED_26_BIT_KHR) },
    { "VK_FORMAT_FEATURE_RESERVED_27_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_RESERVED_27_BIT_KHR) },
    { "VK_FORMAT_FEATURE_RESERVED_28_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_RESERVED_28_BIT_KHR) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT) },
    { "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR) },
    { "VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT) },
    { "VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT) },
    { "VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT) },
    { "VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT) },
    { "VK_FORMAT_FEATURE_TRANSFER_DST_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_TRANSFER_DST_BIT) },
    { "VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR) },
    { "VK_FORMAT_FEATURE_TRANSFER_SRC_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_TRANSFER_SRC_BIT) },
    { "VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR) },
    { "VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT) },
    { "VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT", static_cast<VKbitfield>(VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT) },
    { "VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT_KHR", static_cast<VKbitfield>(VkFramebufferCreateFlagBits::VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT_KHR) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_G =
{
    { "VK_GEOMETRY_INSTANCE_FORCE_NO_OPAQUE_BIT_NV", static_cast<VKbitfield>(VkGeometryInstanceFlagBitsNV::VK_GEOMETRY_INSTANCE_FORCE_NO_OPAQUE_BIT_NV) },
    { "VK_GEOMETRY_INSTANCE_FORCE_OPAQUE_BIT_NV", static_cast<VKbitfield>(VkGeometryInstanceFlagBitsNV::VK_GEOMETRY_INSTANCE_FORCE_OPAQUE_BIT_NV) },
    { "VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV", static_cast<VKbitfield>(VkGeometryInstanceFlagBitsNV::VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV) },
    { "VK_GEOMETRY_INSTANCE_TRIANGLE_FRONT_COUNTERCLOCKWISE_BIT_NV", static_cast<VKbitfield>(VkGeometryInstanceFlagBitsNV::VK_GEOMETRY_INSTANCE_TRIANGLE_FRONT_COUNTERCLOCKWISE_BIT_NV) },
    { "VK_GEOMETRY_NO_DUPLICATE_ANY_HIT_INVOCATION_BIT_NV", static_cast<VKbitfield>(VkGeometryFlagBitsNV::VK_GEOMETRY_NO_DUPLICATE_ANY_HIT_INVOCATION_BIT_NV) },
    { "VK_GEOMETRY_OPAQUE_BIT_NV", static_cast<VKbitfield>(VkGeometryFlagBitsNV::VK_GEOMETRY_OPAQUE_BIT_NV) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_H{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_I =
{
    { "VK_IMAGE_ASPECT_COLOR_BIT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_COLOR_BIT) },
    { "VK_IMAGE_ASPECT_DEPTH_BIT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_DEPTH_BIT) },
    { "VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT) },
    { "VK_IMAGE_ASPECT_MEMORY_PLANE_1_BIT_EXT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_MEMORY_PLANE_1_BIT_EXT) },
    { "VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT) },
    { "VK_IMAGE_ASPECT_MEMORY_PLANE_3_BIT_EXT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_MEMORY_PLANE_3_BIT_EXT) },
    { "VK_IMAGE_ASPECT_METADATA_BIT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_METADATA_BIT) },
    { "VK_IMAGE_ASPECT_PLANE_0_BIT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_0_BIT) },
    { "VK_IMAGE_ASPECT_PLANE_0_BIT_KHR", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_0_BIT_KHR) },
    { "VK_IMAGE_ASPECT_PLANE_1_BIT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_1_BIT) },
    { "VK_IMAGE_ASPECT_PLANE_1_BIT_KHR", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_1_BIT_KHR) },
    { "VK_IMAGE_ASPECT_PLANE_2_BIT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_2_BIT) },
    { "VK_IMAGE_ASPECT_PLANE_2_BIT_KHR", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_2_BIT_KHR) },
    { "VK_IMAGE_ASPECT_STENCIL_BIT", static_cast<VKbitfield>(VkImageAspectFlagBits::VK_IMAGE_ASPECT_STENCIL_BIT) },
    { "VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT) },
    { "VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR) },
    { "VK_IMAGE_CREATE_ALIAS_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_ALIAS_BIT) },
    { "VK_IMAGE_CREATE_ALIAS_BIT_KHR", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_ALIAS_BIT_KHR) },
    { "VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT) },
    { "VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR) },
    { "VK_IMAGE_CREATE_CORNER_SAMPLED_BIT_NV", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_CORNER_SAMPLED_BIT_NV) },
    { "VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT) },
    { "VK_IMAGE_CREATE_DISJOINT_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_DISJOINT_BIT) },
    { "VK_IMAGE_CREATE_DISJOINT_BIT_KHR", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_DISJOINT_BIT_KHR) },
    { "VK_IMAGE_CREATE_EXTENDED_USAGE_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_EXTENDED_USAGE_BIT) },
    { "VK_IMAGE_CREATE_EXTENDED_USAGE_BIT_KHR", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_EXTENDED_USAGE_BIT_KHR) },
    { "VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT) },
    { "VK_IMAGE_CREATE_PROTECTED_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_PROTECTED_BIT) },
    { "VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT) },
    { "VK_IMAGE_CREATE_SPARSE_ALIASED_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_SPARSE_ALIASED_BIT) },
    { "VK_IMAGE_CREATE_SPARSE_BINDING_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_SPARSE_BINDING_BIT) },
    { "VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT) },
    { "VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT) },
    { "VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR) },
    { "VK_IMAGE_CREATE_SUBSAMPLED_BIT_EXT", static_cast<VKbitfield>(VkImageCreateFlagBits::VK_IMAGE_CREATE_SUBSAMPLED_BIT_EXT) },
    { "VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT) },
    { "VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT) },
    { "VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT) },
    { "VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT) },
    { "VK_IMAGE_USAGE_RESERVED_10_BIT_KHR", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_10_BIT_KHR) },
    { "VK_IMAGE_USAGE_RESERVED_11_BIT_KHR", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_11_BIT_KHR) },
    { "VK_IMAGE_USAGE_RESERVED_12_BIT_KHR", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_12_BIT_KHR) },
    { "VK_IMAGE_USAGE_RESERVED_13_BIT_KHR", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_13_BIT_KHR) },
    { "VK_IMAGE_USAGE_RESERVED_14_BIT_KHR", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_14_BIT_KHR) },
    { "VK_IMAGE_USAGE_RESERVED_15_BIT_KHR", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_15_BIT_KHR) },
    { "VK_IMAGE_USAGE_SAMPLED_BIT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_SAMPLED_BIT) },
    { "VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV) },
    { "VK_IMAGE_USAGE_STORAGE_BIT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_STORAGE_BIT) },
    { "VK_IMAGE_USAGE_TRANSFER_DST_BIT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_TRANSFER_DST_BIT) },
    { "VK_IMAGE_USAGE_TRANSFER_SRC_BIT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_TRANSFER_SRC_BIT) },
    { "VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT", static_cast<VKbitfield>(VkImageUsageFlagBits::VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT) },
    { "VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT", static_cast<VKbitfield>(VkImageViewCreateFlagBits::VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT) },
    { "VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EMPTY_EXECUTIONS_BIT_NVX", static_cast<VKbitfield>(VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EMPTY_EXECUTIONS_BIT_NVX) },
    { "VK_INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NVX", static_cast<VKbitfield>(VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NVX) },
    { "VK_INDIRECT_COMMANDS_LAYOUT_USAGE_SPARSE_SEQUENCES_BIT_NVX", static_cast<VKbitfield>(VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_INDIRECT_COMMANDS_LAYOUT_USAGE_SPARSE_SEQUENCES_BIT_NVX) },
    { "VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NVX", static_cast<VKbitfield>(VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NVX) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_J{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_K{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_L{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_M =
{
    { "VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT", static_cast<VKbitfield>(VkMemoryAllocateFlagBits::VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT) },
    { "VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT_KHR", static_cast<VKbitfield>(VkMemoryAllocateFlagBits::VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT_KHR) },
    { "VK_MEMORY_HEAP_DEVICE_LOCAL_BIT", static_cast<VKbitfield>(VkMemoryHeapFlagBits::VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) },
    { "VK_MEMORY_HEAP_MULTI_INSTANCE_BIT", static_cast<VKbitfield>(VkMemoryHeapFlagBits::VK_MEMORY_HEAP_MULTI_INSTANCE_BIT) },
    { "VK_MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR", static_cast<VKbitfield>(VkMemoryHeapFlagBits::VK_MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR) },
    { "VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT", static_cast<VKbitfield>(VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT) },
    { "VK_MEMORY_PROPERTY_HOST_CACHED_BIT", static_cast<VKbitfield>(VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_HOST_CACHED_BIT) },
    { "VK_MEMORY_PROPERTY_HOST_COHERENT_BIT", static_cast<VKbitfield>(VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_HOST_COHERENT_BIT) },
    { "VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT", static_cast<VKbitfield>(VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT) },
    { "VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT", static_cast<VKbitfield>(VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT) },
    { "VK_MEMORY_PROPERTY_PROTECTED_BIT", static_cast<VKbitfield>(VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_PROTECTED_BIT) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_N =
{
    { "VK_NONE_BIT", static_cast<VKbitfield>(VkFramebufferCreateFlagBits::VK_NONE_BIT) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_O =
{
    { "VK_OBJECT_ENTRY_USAGE_COMPUTE_BIT_NVX", static_cast<VKbitfield>(VkObjectEntryUsageFlagBitsNVX::VK_OBJECT_ENTRY_USAGE_COMPUTE_BIT_NVX) },
    { "VK_OBJECT_ENTRY_USAGE_GRAPHICS_BIT_NVX", static_cast<VKbitfield>(VkObjectEntryUsageFlagBitsNVX::VK_OBJECT_ENTRY_USAGE_GRAPHICS_BIT_NVX) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_P =
{
    { "VK_PEER_MEMORY_FEATURE_COPY_DST_BIT", static_cast<VKbitfield>(VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_COPY_DST_BIT) },
    { "VK_PEER_MEMORY_FEATURE_COPY_DST_BIT_KHR", static_cast<VKbitfield>(VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_COPY_DST_BIT_KHR) },
    { "VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT", static_cast<VKbitfield>(VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT) },
    { "VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT_KHR", static_cast<VKbitfield>(VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT_KHR) },
    { "VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT", static_cast<VKbitfield>(VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT) },
    { "VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT_KHR", static_cast<VKbitfield>(VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT_KHR) },
    { "VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT", static_cast<VKbitfield>(VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT) },
    { "VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT_KHR", static_cast<VKbitfield>(VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT_KHR) },
    { "VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT", static_cast<VKbitfield>(VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT) },
    { "VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV", static_cast<VKbitfield>(VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV) },
    { "VK_PIPELINE_CREATE_DERIVATIVE_BIT", static_cast<VKbitfield>(VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DERIVATIVE_BIT) },
    { "VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT", static_cast<VKbitfield>(VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT) },
    { "VK_PIPELINE_CREATE_DISPATCH_BASE", static_cast<VKbitfield>(VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DISPATCH_BASE) },
    { "VK_PIPELINE_CREATE_DISPATCH_BASE_KHR", static_cast<VKbitfield>(VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DISPATCH_BASE_KHR) },
    { "VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT", static_cast<VKbitfield>(VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT) },
    { "VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR", static_cast<VKbitfield>(VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR) },
    { "VK_PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT_EXT", static_cast<VKbitfield>(VkPipelineCreationFeedbackFlagBitsEXT::VK_PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT_EXT) },
    { "VK_PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT_EXT", static_cast<VKbitfield>(VkPipelineCreationFeedbackFlagBitsEXT::VK_PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT_EXT) },
    { "VK_PIPELINE_CREATION_FEEDBACK_VALID_BIT_EXT", static_cast<VKbitfield>(VkPipelineCreationFeedbackFlagBitsEXT::VK_PIPELINE_CREATION_FEEDBACK_VALID_BIT_EXT) },
    { "VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT", static_cast<VKbitfield>(VkPipelineShaderStageCreateFlagBits::VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT) },
    { "VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT", static_cast<VKbitfield>(VkPipelineShaderStageCreateFlagBits::VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT) },
    { "VK_PIPELINE_SHADER_STAGE_CREATE_RESERVED_2_BIT_NV", static_cast<VKbitfield>(VkPipelineShaderStageCreateFlagBits::VK_PIPELINE_SHADER_STAGE_CREATE_RESERVED_2_BIT_NV) },
    { "VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV) },
    { "VK_PIPELINE_STAGE_ALL_COMMANDS_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_ALL_COMMANDS_BIT) },
    { "VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT) },
    { "VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT) },
    { "VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT) },
    { "VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX) },
    { "VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT) },
    { "VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT) },
    { "VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT) },
    { "VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT) },
    { "VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT) },
    { "VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT) },
    { "VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT) },
    { "VK_PIPELINE_STAGE_HOST_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_HOST_BIT) },
    { "VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT) },
    { "VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV) },
    { "VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV) },
    { "VK_PIPELINE_STAGE_RESERVED_26_BIT_KHR", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_RESERVED_26_BIT_KHR) },
    { "VK_PIPELINE_STAGE_RESERVED_27_BIT_KHR", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_RESERVED_27_BIT_KHR) },
    { "VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV) },
    { "VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV) },
    { "VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT) },
    { "VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT) },
    { "VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT) },
    { "VK_PIPELINE_STAGE_TRANSFER_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TRANSFER_BIT) },
    { "VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT) },
    { "VK_PIPELINE_STAGE_VERTEX_INPUT_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) },
    { "VK_PIPELINE_STAGE_VERTEX_SHADER_BIT", static_cast<VKbitfield>(VkPipelineStageFlagBits::VK_PIPELINE_STAGE_VERTEX_SHADER_BIT) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_Q =
{
    { "VK_QUERY_CONTROL_PRECISE_BIT", static_cast<VKbitfield>(VkQueryControlFlagBits::VK_QUERY_CONTROL_PRECISE_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT) },
    { "VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT", static_cast<VKbitfield>(VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT) },
    { "VK_QUERY_RESULT_64_BIT", static_cast<VKbitfield>(VkQueryResultFlagBits::VK_QUERY_RESULT_64_BIT) },
    { "VK_QUERY_RESULT_PARTIAL_BIT", static_cast<VKbitfield>(VkQueryResultFlagBits::VK_QUERY_RESULT_PARTIAL_BIT) },
    { "VK_QUERY_RESULT_WAIT_BIT", static_cast<VKbitfield>(VkQueryResultFlagBits::VK_QUERY_RESULT_WAIT_BIT) },
    { "VK_QUERY_RESULT_WITH_AVAILABILITY_BIT", static_cast<VKbitfield>(VkQueryResultFlagBits::VK_QUERY_RESULT_WITH_AVAILABILITY_BIT) },
    { "VK_QUEUE_COMPUTE_BIT", static_cast<VKbitfield>(VkQueueFlagBits::VK_QUEUE_COMPUTE_BIT) },
    { "VK_QUEUE_GRAPHICS_BIT", static_cast<VKbitfield>(VkQueueFlagBits::VK_QUEUE_GRAPHICS_BIT) },
    { "VK_QUEUE_PROTECTED_BIT", static_cast<VKbitfield>(VkQueueFlagBits::VK_QUEUE_PROTECTED_BIT) },
    { "VK_QUEUE_RESERVED_5_BIT_KHR", static_cast<VKbitfield>(VkQueueFlagBits::VK_QUEUE_RESERVED_5_BIT_KHR) },
    { "VK_QUEUE_RESERVED_6_BIT_KHR", static_cast<VKbitfield>(VkQueueFlagBits::VK_QUEUE_RESERVED_6_BIT_KHR) },
    { "VK_QUEUE_SPARSE_BINDING_BIT", static_cast<VKbitfield>(VkQueueFlagBits::VK_QUEUE_SPARSE_BINDING_BIT) },
    { "VK_QUEUE_TRANSFER_BIT", static_cast<VKbitfield>(VkQueueFlagBits::VK_QUEUE_TRANSFER_BIT) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_R =
{
    { "VK_RENDER_PASS_CREATE_RESERVED_0_BIT_KHR", static_cast<VKbitfield>(VkRenderPassCreateFlagBits::VK_RENDER_PASS_CREATE_RESERVED_0_BIT_KHR) },
    { "VK_RENDER_PASS_RESERVED_BIT_1_QCOM", static_cast<VKbitfield>(VkRenderPassCreateFlagBits::VK_RENDER_PASS_RESERVED_BIT_1_QCOM) },
    { "VK_RESOLVE_MODE_AVERAGE_BIT_KHR", static_cast<VKbitfield>(VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_AVERAGE_BIT_KHR) },
    { "VK_RESOLVE_MODE_MAX_BIT_KHR", static_cast<VKbitfield>(VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_MAX_BIT_KHR) },
    { "VK_RESOLVE_MODE_MIN_BIT_KHR", static_cast<VKbitfield>(VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_MIN_BIT_KHR) },
    { "VK_RESOLVE_MODE_NONE_KHR", static_cast<VKbitfield>(VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_NONE_KHR) },
    { "VK_RESOLVE_MODE_SAMPLE_ZERO_BIT_KHR", static_cast<VKbitfield>(VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_SAMPLE_ZERO_BIT_KHR) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_S =
{
    { "VK_SAMPLE_COUNT_16_BIT", static_cast<VKbitfield>(VkSampleCountFlagBits::VK_SAMPLE_COUNT_16_BIT) },
    { "VK_SAMPLE_COUNT_1_BIT", static_cast<VKbitfield>(VkSampleCountFlagBits::VK_SAMPLE_COUNT_1_BIT) },
    { "VK_SAMPLE_COUNT_2_BIT", static_cast<VKbitfield>(VkSampleCountFlagBits::VK_SAMPLE_COUNT_2_BIT) },
    { "VK_SAMPLE_COUNT_32_BIT", static_cast<VKbitfield>(VkSampleCountFlagBits::VK_SAMPLE_COUNT_32_BIT) },
    { "VK_SAMPLE_COUNT_4_BIT", static_cast<VKbitfield>(VkSampleCountFlagBits::VK_SAMPLE_COUNT_4_BIT) },
    { "VK_SAMPLE_COUNT_64_BIT", static_cast<VKbitfield>(VkSampleCountFlagBits::VK_SAMPLE_COUNT_64_BIT) },
    { "VK_SAMPLE_COUNT_8_BIT", static_cast<VKbitfield>(VkSampleCountFlagBits::VK_SAMPLE_COUNT_8_BIT) },
    { "VK_SAMPLER_CREATE_SUBSAMPLED_BIT_EXT", static_cast<VKbitfield>(VkSamplerCreateFlagBits::VK_SAMPLER_CREATE_SUBSAMPLED_BIT_EXT) },
    { "VK_SAMPLER_CREATE_SUBSAMPLED_COARSE_RECONSTRUCTION_BIT_EXT", static_cast<VKbitfield>(VkSamplerCreateFlagBits::VK_SAMPLER_CREATE_SUBSAMPLED_COARSE_RECONSTRUCTION_BIT_EXT) },
    { "VK_SEMAPHORE_IMPORT_TEMPORARY_BIT", static_cast<VKbitfield>(VkSemaphoreImportFlagBits::VK_SEMAPHORE_IMPORT_TEMPORARY_BIT) },
    { "VK_SEMAPHORE_IMPORT_TEMPORARY_BIT_KHR", static_cast<VKbitfield>(VkSemaphoreImportFlagBits::VK_SEMAPHORE_IMPORT_TEMPORARY_BIT_KHR) },
    { "VK_SHADER_MODULE_CREATE_RESERVED_0_BIT_NV", static_cast<VKbitfield>(VkShaderModuleCreateFlagBits::VK_SHADER_MODULE_CREATE_RESERVED_0_BIT_NV) },
    { "VK_SHADER_STAGE_ALL", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_ALL) },
    { "VK_SHADER_STAGE_ALL_GRAPHICS", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_ALL_GRAPHICS) },
    { "VK_SHADER_STAGE_ANY_HIT_BIT_NV", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_ANY_HIT_BIT_NV) },
    { "VK_SHADER_STAGE_CALLABLE_BIT_NV", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_CALLABLE_BIT_NV) },
    { "VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV) },
    { "VK_SHADER_STAGE_COMPUTE_BIT", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_COMPUTE_BIT) },
    { "VK_SHADER_STAGE_FRAGMENT_BIT", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_FRAGMENT_BIT) },
    { "VK_SHADER_STAGE_GEOMETRY_BIT", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_GEOMETRY_BIT) },
    { "VK_SHADER_STAGE_INTERSECTION_BIT_NV", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_INTERSECTION_BIT_NV) },
    { "VK_SHADER_STAGE_MESH_BIT_NV", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_MESH_BIT_NV) },
    { "VK_SHADER_STAGE_MISS_BIT_NV", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_MISS_BIT_NV) },
    { "VK_SHADER_STAGE_RAYGEN_BIT_NV", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_RAYGEN_BIT_NV) },
    { "VK_SHADER_STAGE_TASK_BIT_NV", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_TASK_BIT_NV) },
    { "VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT) },
    { "VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT) },
    { "VK_SHADER_STAGE_VERTEX_BIT", static_cast<VKbitfield>(VkShaderStageFlagBits::VK_SHADER_STAGE_VERTEX_BIT) },
    { "VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT", static_cast<VKbitfield>(VkSparseImageFormatFlagBits::VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT) },
    { "VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT", static_cast<VKbitfield>(VkSparseImageFormatFlagBits::VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT) },
    { "VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT", static_cast<VKbitfield>(VkSparseImageFormatFlagBits::VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT) },
    { "VK_SPARSE_MEMORY_BIND_METADATA_BIT", static_cast<VKbitfield>(VkSparseMemoryBindFlagBits::VK_SPARSE_MEMORY_BIND_METADATA_BIT) },
    { "VK_STENCIL_FACE_BACK_BIT", static_cast<VKbitfield>(VkStencilFaceFlagBits::VK_STENCIL_FACE_BACK_BIT) },
    { "VK_STENCIL_FACE_FRONT_AND_BACK", static_cast<VKbitfield>(VkStencilFaceFlagBits::VK_STENCIL_FACE_FRONT_AND_BACK) },
    { "VK_STENCIL_FACE_FRONT_BIT", static_cast<VKbitfield>(VkStencilFaceFlagBits::VK_STENCIL_FACE_FRONT_BIT) },
    { "VK_STENCIL_FRONT_AND_BACK", static_cast<VKbitfield>(VkStencilFaceFlagBits::VK_STENCIL_FRONT_AND_BACK) },
    { "VK_SUBGROUP_FEATURE_ARITHMETIC_BIT", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_ARITHMETIC_BIT) },
    { "VK_SUBGROUP_FEATURE_BALLOT_BIT", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_BALLOT_BIT) },
    { "VK_SUBGROUP_FEATURE_BASIC_BIT", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_BASIC_BIT) },
    { "VK_SUBGROUP_FEATURE_CLUSTERED_BIT", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_CLUSTERED_BIT) },
    { "VK_SUBGROUP_FEATURE_PARTITIONED_BIT_NV", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_PARTITIONED_BIT_NV) },
    { "VK_SUBGROUP_FEATURE_QUAD_BIT", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_QUAD_BIT) },
    { "VK_SUBGROUP_FEATURE_SHUFFLE_BIT", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_SHUFFLE_BIT) },
    { "VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT) },
    { "VK_SUBGROUP_FEATURE_VOTE_BIT", static_cast<VKbitfield>(VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_VOTE_BIT) },
    { "VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX", static_cast<VKbitfield>(VkSubpassDescriptionFlagBits::VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX) },
    { "VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX", static_cast<VKbitfield>(VkSubpassDescriptionFlagBits::VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX) },
    { "VK_SUBPASS_DESCRIPTION_RESERVED_2_BIT_QCOM", static_cast<VKbitfield>(VkSubpassDescriptionFlagBits::VK_SUBPASS_DESCRIPTION_RESERVED_2_BIT_QCOM) },
    { "VK_SUBPASS_DESCRIPTION_RESERVED_3_BIT_QCOM", static_cast<VKbitfield>(VkSubpassDescriptionFlagBits::VK_SUBPASS_DESCRIPTION_RESERVED_3_BIT_QCOM) },
    { "VK_SURFACE_COUNTER_VBLANK_EXT", static_cast<VKbitfield>(VkSurfaceCounterFlagBitsEXT::VK_SURFACE_COUNTER_VBLANK_EXT) },
    { "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR) },
    { "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR) },
    { "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR) },
    { "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR) },
    { "VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR) },
    { "VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR) },
    { "VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR) },
    { "VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR) },
    { "VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR", static_cast<VKbitfield>(VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR) },
    { "VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR", static_cast<VKbitfield>(VkSwapchainCreateFlagBitsKHR::VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR) },
    { "VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR", static_cast<VKbitfield>(VkSwapchainCreateFlagBitsKHR::VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR) },
    { "VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR", static_cast<VKbitfield>(VkSwapchainCreateFlagBitsKHR::VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR) },
    { "VK_SWAPCHAIN_IMAGE_USAGE_SHARED_BIT_ANDROID", static_cast<VKbitfield>(VkSwapchainImageUsageFlagBitsANDROID::VK_SWAPCHAIN_IMAGE_USAGE_SHARED_BIT_ANDROID) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_T{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_U =
{
    { "GL_UNUSED_BIT", static_cast<VKbitfield>(UnusedMask::GL_UNUSED_BIT) }
};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_V{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_W{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_X{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_Y{};

const std::unordered_map<std::string, VKbitfield> Meta_BitfieldsByString_Z{};

const std::array<std::unordered_map<std::string, vk::VKbitfield>, 27> Meta_BitfieldsByStringMaps =
{ {
    Meta_BitfieldsByString_0,
    Meta_BitfieldsByString_A,
    Meta_BitfieldsByString_B,
    Meta_BitfieldsByString_C,
    Meta_BitfieldsByString_D,
    Meta_BitfieldsByString_E,
    Meta_BitfieldsByString_F,
    Meta_BitfieldsByString_G,
    Meta_BitfieldsByString_H,
    Meta_BitfieldsByString_I,
    Meta_BitfieldsByString_J,
    Meta_BitfieldsByString_K,
    Meta_BitfieldsByString_L,
    Meta_BitfieldsByString_M,
    Meta_BitfieldsByString_N,
    Meta_BitfieldsByString_O,
    Meta_BitfieldsByString_P,
    Meta_BitfieldsByString_Q,
    Meta_BitfieldsByString_R,
    Meta_BitfieldsByString_S,
    Meta_BitfieldsByString_T,
    Meta_BitfieldsByString_U,
    Meta_BitfieldsByString_V,
    Meta_BitfieldsByString_W,
    Meta_BitfieldsByString_X,
    Meta_BitfieldsByString_Y,
    Meta_BitfieldsByString_Z
} };


} } // namespace vkbinding::aux