
#include "Meta_Maps.h"

#include <vkbinding/vk/bitfield.h>


using namespace vk;


namespace vkbinding { namespace aux
{


const std::unordered_map<UnusedMask, std::string> Meta_StringsByUnusedMask =
{
    { UnusedMask::GL_UNUSED_BIT, "GL_UNUSED_BIT" }
};

const std::unordered_map<VkAccessFlagBits, std::string> Meta_StringsByVkAccessFlagBits =
{
    { VkAccessFlagBits::VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV, "VK_ACCESS_ACCELERATION_STRUCTURE_READ_BIT_NV" },
    { VkAccessFlagBits::VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_NV, "VK_ACCESS_ACCELERATION_STRUCTURE_WRITE_BIT_NV" },
    { VkAccessFlagBits::VK_ACCESS_COLOR_ATTACHMENT_READ_BIT, "VK_ACCESS_COLOR_ATTACHMENT_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT, "VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT" },
    { VkAccessFlagBits::VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT, "VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT" },
    { VkAccessFlagBits::VK_ACCESS_COMMAND_PROCESS_READ_BIT_NVX, "VK_ACCESS_COMMAND_PROCESS_READ_BIT_NVX" },
    { VkAccessFlagBits::VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX, "VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX" },
    { VkAccessFlagBits::VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT, "VK_ACCESS_CONDITIONAL_RENDERING_READ_BIT_EXT" },
    { VkAccessFlagBits::VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT, "VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT, "VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT" },
    { VkAccessFlagBits::VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT, "VK_ACCESS_FRAGMENT_DENSITY_MAP_READ_BIT_EXT" },
    { VkAccessFlagBits::VK_ACCESS_HOST_READ_BIT, "VK_ACCESS_HOST_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_HOST_WRITE_BIT, "VK_ACCESS_HOST_WRITE_BIT" },
    { VkAccessFlagBits::VK_ACCESS_INDEX_READ_BIT, "VK_ACCESS_INDEX_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_INDIRECT_COMMAND_READ_BIT, "VK_ACCESS_INDIRECT_COMMAND_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_INPUT_ATTACHMENT_READ_BIT, "VK_ACCESS_INPUT_ATTACHMENT_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_MEMORY_READ_BIT, "VK_ACCESS_MEMORY_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_MEMORY_WRITE_BIT, "VK_ACCESS_MEMORY_WRITE_BIT" },
    { VkAccessFlagBits::VK_ACCESS_RESERVED_28_BIT_KHR, "VK_ACCESS_RESERVED_28_BIT_KHR" },
    { VkAccessFlagBits::VK_ACCESS_RESERVED_29_BIT_KHR, "VK_ACCESS_RESERVED_29_BIT_KHR" },
    { VkAccessFlagBits::VK_ACCESS_RESERVED_30_BIT_KHR, "VK_ACCESS_RESERVED_30_BIT_KHR" },
    { VkAccessFlagBits::VK_ACCESS_RESERVED_31_BIT_KHR, "VK_ACCESS_RESERVED_31_BIT_KHR" },
    { VkAccessFlagBits::VK_ACCESS_SHADER_READ_BIT, "VK_ACCESS_SHADER_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_SHADER_WRITE_BIT, "VK_ACCESS_SHADER_WRITE_BIT" },
    { VkAccessFlagBits::VK_ACCESS_SHADING_RATE_IMAGE_READ_BIT_NV, "VK_ACCESS_SHADING_RATE_IMAGE_READ_BIT_NV" },
    { VkAccessFlagBits::VK_ACCESS_TRANSFER_READ_BIT, "VK_ACCESS_TRANSFER_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_TRANSFER_WRITE_BIT, "VK_ACCESS_TRANSFER_WRITE_BIT" },
    { VkAccessFlagBits::VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT, "VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_READ_BIT_EXT" },
    { VkAccessFlagBits::VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT, "VK_ACCESS_TRANSFORM_FEEDBACK_COUNTER_WRITE_BIT_EXT" },
    { VkAccessFlagBits::VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT, "VK_ACCESS_TRANSFORM_FEEDBACK_WRITE_BIT_EXT" },
    { VkAccessFlagBits::VK_ACCESS_UNIFORM_READ_BIT, "VK_ACCESS_UNIFORM_READ_BIT" },
    { VkAccessFlagBits::VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT, "VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT" },
    { VkAccessFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkAttachmentDescriptionFlagBits, std::string> Meta_StringsByVkAttachmentDescriptionFlagBits =
{
    { VkAttachmentDescriptionFlagBits::VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT, "VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT" },
    { VkAttachmentDescriptionFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkBufferCreateFlagBits, std::string> Meta_StringsByVkBufferCreateFlagBits =
{
    { VkBufferCreateFlagBits::VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT, "VK_BUFFER_CREATE_DEVICE_ADDRESS_CAPTURE_REPLAY_BIT_EXT" },
    { VkBufferCreateFlagBits::VK_BUFFER_CREATE_PROTECTED_BIT, "VK_BUFFER_CREATE_PROTECTED_BIT" },
    { VkBufferCreateFlagBits::VK_BUFFER_CREATE_SPARSE_ALIASED_BIT, "VK_BUFFER_CREATE_SPARSE_ALIASED_BIT" },
    { VkBufferCreateFlagBits::VK_BUFFER_CREATE_SPARSE_BINDING_BIT, "VK_BUFFER_CREATE_SPARSE_BINDING_BIT" },
    { VkBufferCreateFlagBits::VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT, "VK_BUFFER_CREATE_SPARSE_RESIDENCY_BIT" },
    { VkBufferCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkBufferUsageFlagBits, std::string> Meta_StringsByVkBufferUsageFlagBits =
{
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT, "VK_BUFFER_USAGE_CONDITIONAL_RENDERING_BIT_EXT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_INDEX_BUFFER_BIT, "VK_BUFFER_USAGE_INDEX_BUFFER_BIT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT, "VK_BUFFER_USAGE_INDIRECT_BUFFER_BIT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_RAY_TRACING_BIT_NV, "VK_BUFFER_USAGE_RAY_TRACING_BIT_NV" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_RESERVED_13_BIT_KHR, "VK_BUFFER_USAGE_RESERVED_13_BIT_KHR" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_RESERVED_14_BIT_KHR, "VK_BUFFER_USAGE_RESERVED_14_BIT_KHR" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_RESERVED_15_BIT_KHR, "VK_BUFFER_USAGE_RESERVED_15_BIT_KHR" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_RESERVED_16_BIT_KHR, "VK_BUFFER_USAGE_RESERVED_16_BIT_KHR" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_EXT, "VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT_EXT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_STORAGE_BUFFER_BIT, "VK_BUFFER_USAGE_STORAGE_BUFFER_BIT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT, "VK_BUFFER_USAGE_STORAGE_TEXEL_BUFFER_BIT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_TRANSFER_DST_BIT, "VK_BUFFER_USAGE_TRANSFER_DST_BIT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_TRANSFER_SRC_BIT, "VK_BUFFER_USAGE_TRANSFER_SRC_BIT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT, "VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_BUFFER_BIT_EXT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT, "VK_BUFFER_USAGE_TRANSFORM_FEEDBACK_COUNTER_BUFFER_BIT_EXT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT, "VK_BUFFER_USAGE_UNIFORM_BUFFER_BIT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT, "VK_BUFFER_USAGE_UNIFORM_TEXEL_BUFFER_BIT" },
    { VkBufferUsageFlagBits::VK_BUFFER_USAGE_VERTEX_BUFFER_BIT, "VK_BUFFER_USAGE_VERTEX_BUFFER_BIT" },
    { VkBufferUsageFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkBufferViewCreateFlagBits, std::string> Meta_StringsByVkBufferViewCreateFlagBits =
{
    { VkBufferViewCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkBuildAccelerationStructureFlagBitsNV, std::string> Meta_StringsByVkBuildAccelerationStructureFlagBitsNV =
{
    { VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV, "VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV" },
    { VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV, "VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV" },
    { VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV, "VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV" },
    { VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV, "VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV" },
    { VkBuildAccelerationStructureFlagBitsNV::VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV, "VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV" },
    { VkBuildAccelerationStructureFlagBitsNV::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkColorComponentFlagBits, std::string> Meta_StringsByVkColorComponentFlagBits =
{
    { VkColorComponentFlagBits::VK_COLOR_COMPONENT_A_BIT, "VK_COLOR_COMPONENT_A_BIT" },
    { VkColorComponentFlagBits::VK_COLOR_COMPONENT_B_BIT, "VK_COLOR_COMPONENT_B_BIT" },
    { VkColorComponentFlagBits::VK_COLOR_COMPONENT_G_BIT, "VK_COLOR_COMPONENT_G_BIT" },
    { VkColorComponentFlagBits::VK_COLOR_COMPONENT_R_BIT, "VK_COLOR_COMPONENT_R_BIT" },
    { VkColorComponentFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkCommandBufferResetFlagBits, std::string> Meta_StringsByVkCommandBufferResetFlagBits =
{
    { VkCommandBufferResetFlagBits::VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT, "VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT" },
    { VkCommandBufferResetFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkCommandBufferUsageFlagBits, std::string> Meta_StringsByVkCommandBufferUsageFlagBits =
{
    { VkCommandBufferUsageFlagBits::VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT, "VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT" },
    { VkCommandBufferUsageFlagBits::VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT, "VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT" },
    { VkCommandBufferUsageFlagBits::VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT, "VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT" },
    { VkCommandBufferUsageFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkCommandPoolCreateFlagBits, std::string> Meta_StringsByVkCommandPoolCreateFlagBits =
{
    { VkCommandPoolCreateFlagBits::VK_COMMAND_POOL_CREATE_PROTECTED_BIT, "VK_COMMAND_POOL_CREATE_PROTECTED_BIT" },
    { VkCommandPoolCreateFlagBits::VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT, "VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT" },
    { VkCommandPoolCreateFlagBits::VK_COMMAND_POOL_CREATE_TRANSIENT_BIT, "VK_COMMAND_POOL_CREATE_TRANSIENT_BIT" },
    { VkCommandPoolCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkCommandPoolResetFlagBits, std::string> Meta_StringsByVkCommandPoolResetFlagBits =
{
    { VkCommandPoolResetFlagBits::VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT, "VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT" },
    { VkCommandPoolResetFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkCompositeAlphaFlagBitsKHR, std::string> Meta_StringsByVkCompositeAlphaFlagBitsKHR =
{
    { VkCompositeAlphaFlagBitsKHR::VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR, "VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR" },
    { VkCompositeAlphaFlagBitsKHR::VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR, "VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR" },
    { VkCompositeAlphaFlagBitsKHR::VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR, "VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR" },
    { VkCompositeAlphaFlagBitsKHR::VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR, "VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR" },
    { VkCompositeAlphaFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkConditionalRenderingFlagBitsEXT, std::string> Meta_StringsByVkConditionalRenderingFlagBitsEXT =
{
    { VkConditionalRenderingFlagBitsEXT::VK_CONDITIONAL_RENDERING_INVERTED_BIT_EXT, "VK_CONDITIONAL_RENDERING_INVERTED_BIT_EXT" },
    { VkConditionalRenderingFlagBitsEXT::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkCullModeFlagBits, std::string> Meta_StringsByVkCullModeFlagBits =
{
    { VkCullModeFlagBits::VK_CULL_MODE_BACK_BIT, "VK_CULL_MODE_BACK_BIT" },
    { VkCullModeFlagBits::VK_CULL_MODE_FRONT_AND_BACK, "VK_CULL_MODE_FRONT_AND_BACK" },
    { VkCullModeFlagBits::VK_CULL_MODE_FRONT_BIT, "VK_CULL_MODE_FRONT_BIT" },
    { VkCullModeFlagBits::VK_CULL_MODE_NONE, "VK_CULL_MODE_NONE" },
    { VkCullModeFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDebugReportFlagBitsEXT, std::string> Meta_StringsByVkDebugReportFlagBitsEXT =
{
    { VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_DEBUG_BIT_EXT, "VK_DEBUG_REPORT_DEBUG_BIT_EXT" },
    { VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_ERROR_BIT_EXT, "VK_DEBUG_REPORT_ERROR_BIT_EXT" },
    { VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_INFORMATION_BIT_EXT, "VK_DEBUG_REPORT_INFORMATION_BIT_EXT" },
    { VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT, "VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT" },
    { VkDebugReportFlagBitsEXT::VK_DEBUG_REPORT_WARNING_BIT_EXT, "VK_DEBUG_REPORT_WARNING_BIT_EXT" },
    { VkDebugReportFlagBitsEXT::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDebugUtilsMessageSeverityFlagBitsEXT, std::string> Meta_StringsByVkDebugUtilsMessageSeverityFlagBitsEXT =
{
    { VkDebugUtilsMessageSeverityFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT, "VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT" },
    { VkDebugUtilsMessageSeverityFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT, "VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT" },
    { VkDebugUtilsMessageSeverityFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT, "VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT" },
    { VkDebugUtilsMessageSeverityFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT, "VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT" },
    { VkDebugUtilsMessageSeverityFlagBitsEXT::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDebugUtilsMessageTypeFlagBitsEXT, std::string> Meta_StringsByVkDebugUtilsMessageTypeFlagBitsEXT =
{
    { VkDebugUtilsMessageTypeFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT, "VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT" },
    { VkDebugUtilsMessageTypeFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT, "VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT" },
    { VkDebugUtilsMessageTypeFlagBitsEXT::VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT, "VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT" },
    { VkDebugUtilsMessageTypeFlagBitsEXT::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDependencyFlagBits, std::string> Meta_StringsByVkDependencyFlagBits =
{
    { VkDependencyFlagBits::VK_DEPENDENCY_BY_REGION_BIT, "VK_DEPENDENCY_BY_REGION_BIT" },
    { VkDependencyFlagBits::VK_DEPENDENCY_DEVICE_GROUP_BIT, "VK_DEPENDENCY_DEVICE_GROUP_BIT" },
    { VkDependencyFlagBits::VK_DEPENDENCY_DEVICE_GROUP_BIT_KHR, "VK_DEPENDENCY_DEVICE_GROUP_BIT_KHR" },
    { VkDependencyFlagBits::VK_DEPENDENCY_VIEW_LOCAL_BIT, "VK_DEPENDENCY_VIEW_LOCAL_BIT" },
    { VkDependencyFlagBits::VK_DEPENDENCY_VIEW_LOCAL_BIT_KHR, "VK_DEPENDENCY_VIEW_LOCAL_BIT_KHR" },
    { VkDependencyFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDescriptorBindingFlagBitsEXT, std::string> Meta_StringsByVkDescriptorBindingFlagBitsEXT =
{
    { VkDescriptorBindingFlagBitsEXT::VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT, "VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT" },
    { VkDescriptorBindingFlagBitsEXT::VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT, "VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT" },
    { VkDescriptorBindingFlagBitsEXT::VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT, "VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT" },
    { VkDescriptorBindingFlagBitsEXT::VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT, "VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT" },
    { VkDescriptorBindingFlagBitsEXT::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDescriptorPoolCreateFlagBits, std::string> Meta_StringsByVkDescriptorPoolCreateFlagBits =
{
    { VkDescriptorPoolCreateFlagBits::VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT, "VK_DESCRIPTOR_POOL_CREATE_FREE_DESCRIPTOR_SET_BIT" },
    { VkDescriptorPoolCreateFlagBits::VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT_EXT, "VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT_EXT" },
    { VkDescriptorPoolCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDescriptorSetLayoutCreateFlagBits, std::string> Meta_StringsByVkDescriptorSetLayoutCreateFlagBits =
{
    { VkDescriptorSetLayoutCreateFlagBits::VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR, "VK_DESCRIPTOR_SET_LAYOUT_CREATE_PUSH_DESCRIPTOR_BIT_KHR" },
    { VkDescriptorSetLayoutCreateFlagBits::VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT, "VK_DESCRIPTOR_SET_LAYOUT_CREATE_UPDATE_AFTER_BIND_POOL_BIT_EXT" },
    { VkDescriptorSetLayoutCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDeviceCreateFlagBits, std::string> Meta_StringsByVkDeviceCreateFlagBits =
{
    { VkDeviceCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDeviceGroupPresentModeFlagBitsKHR, std::string> Meta_StringsByVkDeviceGroupPresentModeFlagBitsKHR =
{
    { VkDeviceGroupPresentModeFlagBitsKHR::VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR, "VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR" },
    { VkDeviceGroupPresentModeFlagBitsKHR::VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR, "VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR" },
    { VkDeviceGroupPresentModeFlagBitsKHR::VK_DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR, "VK_DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR" },
    { VkDeviceGroupPresentModeFlagBitsKHR::VK_DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR, "VK_DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR" },
    { VkDeviceGroupPresentModeFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDeviceQueueCreateFlagBits, std::string> Meta_StringsByVkDeviceQueueCreateFlagBits =
{
    { VkDeviceQueueCreateFlagBits::VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT, "VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT" },
    { VkDeviceQueueCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkDisplayPlaneAlphaFlagBitsKHR, std::string> Meta_StringsByVkDisplayPlaneAlphaFlagBitsKHR =
{
    { VkDisplayPlaneAlphaFlagBitsKHR::VK_DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR, "VK_DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR" },
    { VkDisplayPlaneAlphaFlagBitsKHR::VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR, "VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR" },
    { VkDisplayPlaneAlphaFlagBitsKHR::VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR, "VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR" },
    { VkDisplayPlaneAlphaFlagBitsKHR::VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR, "VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR" },
    { VkDisplayPlaneAlphaFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalFenceFeatureFlagBits, std::string> Meta_StringsByVkExternalFenceFeatureFlagBits =
{
    { VkExternalFenceFeatureFlagBits::VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT, "VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT" },
    { VkExternalFenceFeatureFlagBits::VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT_KHR, "VK_EXTERNAL_FENCE_FEATURE_EXPORTABLE_BIT_KHR" },
    { VkExternalFenceFeatureFlagBits::VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT, "VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT" },
    { VkExternalFenceFeatureFlagBits::VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT_KHR, "VK_EXTERNAL_FENCE_FEATURE_IMPORTABLE_BIT_KHR" },
    { VkExternalFenceFeatureFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalFenceFeatureFlagBitsKHR, std::string> Meta_StringsByVkExternalFenceFeatureFlagBitsKHR =
{
    { VkExternalFenceFeatureFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalFenceHandleTypeFlagBits, std::string> Meta_StringsByVkExternalFenceHandleTypeFlagBits =
{
    { VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT, "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT" },
    { VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR, "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR" },
    { VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT, "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT" },
    { VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR, "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR" },
    { VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT, "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT" },
    { VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR, "VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR" },
    { VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT, "VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT" },
    { VkExternalFenceHandleTypeFlagBits::VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT_KHR, "VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT_KHR" },
    { VkExternalFenceHandleTypeFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalFenceHandleTypeFlagBitsKHR, std::string> Meta_StringsByVkExternalFenceHandleTypeFlagBitsKHR =
{
    { VkExternalFenceHandleTypeFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalMemoryFeatureFlagBits, std::string> Meta_StringsByVkExternalMemoryFeatureFlagBits =
{
    { VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT, "VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT" },
    { VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_KHR, "VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_KHR" },
    { VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT, "VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT" },
    { VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_KHR, "VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_KHR" },
    { VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT, "VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT" },
    { VkExternalMemoryFeatureFlagBits::VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_KHR, "VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_KHR" },
    { VkExternalMemoryFeatureFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalMemoryFeatureFlagBitsKHR, std::string> Meta_StringsByVkExternalMemoryFeatureFlagBitsKHR =
{
    { VkExternalMemoryFeatureFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalMemoryFeatureFlagBitsNV, std::string> Meta_StringsByVkExternalMemoryFeatureFlagBitsNV =
{
    { VkExternalMemoryFeatureFlagBitsNV::VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_NV, "VK_EXTERNAL_MEMORY_FEATURE_DEDICATED_ONLY_BIT_NV" },
    { VkExternalMemoryFeatureFlagBitsNV::VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_NV, "VK_EXTERNAL_MEMORY_FEATURE_EXPORTABLE_BIT_NV" },
    { VkExternalMemoryFeatureFlagBitsNV::VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_NV, "VK_EXTERNAL_MEMORY_FEATURE_IMPORTABLE_BIT_NV" },
    { VkExternalMemoryFeatureFlagBitsNV::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalMemoryHandleTypeFlagBits, std::string> Meta_StringsByVkExternalMemoryHandleTypeFlagBits =
{
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_ANDROID_HARDWARE_BUFFER_BIT_ANDROID" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT_KHR, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_BIT_KHR" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT_KHR, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_TEXTURE_KMT_BIT_KHR" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT_KHR, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_HEAP_BIT_KHR" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT_KHR, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D12_RESOURCE_BIT_KHR" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_DMA_BUF_BIT_EXT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_ALLOCATION_BIT_EXT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_MAPPED_FOREIGN_MEMORY_BIT_EXT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_HOST_MAPPED_FOREIGN_MEMORY_BIT_EXT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT_KHR, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT_KHR" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT" },
    { VkExternalMemoryHandleTypeFlagBits::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR" },
    { VkExternalMemoryHandleTypeFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalMemoryHandleTypeFlagBitsKHR, std::string> Meta_StringsByVkExternalMemoryHandleTypeFlagBitsKHR =
{
    { VkExternalMemoryHandleTypeFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalMemoryHandleTypeFlagBitsNV, std::string> Meta_StringsByVkExternalMemoryHandleTypeFlagBitsNV =
{
    { VkExternalMemoryHandleTypeFlagBitsNV::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_BIT_NV, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_BIT_NV" },
    { VkExternalMemoryHandleTypeFlagBitsNV::VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_KMT_BIT_NV, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_D3D11_IMAGE_KMT_BIT_NV" },
    { VkExternalMemoryHandleTypeFlagBitsNV::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_NV, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_BIT_NV" },
    { VkExternalMemoryHandleTypeFlagBitsNV::VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_NV, "VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_NV" },
    { VkExternalMemoryHandleTypeFlagBitsNV::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalSemaphoreFeatureFlagBits, std::string> Meta_StringsByVkExternalSemaphoreFeatureFlagBits =
{
    { VkExternalSemaphoreFeatureFlagBits::VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT, "VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT" },
    { VkExternalSemaphoreFeatureFlagBits::VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT_KHR, "VK_EXTERNAL_SEMAPHORE_FEATURE_EXPORTABLE_BIT_KHR" },
    { VkExternalSemaphoreFeatureFlagBits::VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT, "VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT" },
    { VkExternalSemaphoreFeatureFlagBits::VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT_KHR, "VK_EXTERNAL_SEMAPHORE_FEATURE_IMPORTABLE_BIT_KHR" },
    { VkExternalSemaphoreFeatureFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalSemaphoreFeatureFlagBitsKHR, std::string> Meta_StringsByVkExternalSemaphoreFeatureFlagBitsKHR =
{
    { VkExternalSemaphoreFeatureFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalSemaphoreHandleTypeFlagBits, std::string> Meta_StringsByVkExternalSemaphoreHandleTypeFlagBits =
{
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT_KHR, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_D3D12_FENCE_BIT_KHR" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT_KHR" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_BIT_KHR" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_WIN32_KMT_BIT_KHR" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT_KHR, "VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT_KHR" },
    { VkExternalSemaphoreHandleTypeFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkExternalSemaphoreHandleTypeFlagBitsKHR, std::string> Meta_StringsByVkExternalSemaphoreHandleTypeFlagBitsKHR =
{
    { VkExternalSemaphoreHandleTypeFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkFenceCreateFlagBits, std::string> Meta_StringsByVkFenceCreateFlagBits =
{
    { VkFenceCreateFlagBits::VK_FENCE_CREATE_SIGNALED_BIT, "VK_FENCE_CREATE_SIGNALED_BIT" },
    { VkFenceCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkFenceImportFlagBits, std::string> Meta_StringsByVkFenceImportFlagBits =
{
    { VkFenceImportFlagBits::VK_FENCE_IMPORT_TEMPORARY_BIT, "VK_FENCE_IMPORT_TEMPORARY_BIT" },
    { VkFenceImportFlagBits::VK_FENCE_IMPORT_TEMPORARY_BIT_KHR, "VK_FENCE_IMPORT_TEMPORARY_BIT_KHR" },
    { VkFenceImportFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkFenceImportFlagBitsKHR, std::string> Meta_StringsByVkFenceImportFlagBitsKHR =
{
    { VkFenceImportFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkFormatFeatureFlagBits, std::string> Meta_StringsByVkFormatFeatureFlagBits =
{
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_BLIT_DST_BIT, "VK_FORMAT_FEATURE_BLIT_DST_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_BLIT_SRC_BIT, "VK_FORMAT_FEATURE_BLIT_SRC_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT, "VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT, "VK_FORMAT_FEATURE_COLOR_ATTACHMENT_BLEND_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT, "VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR, "VK_FORMAT_FEATURE_COSITED_CHROMA_SAMPLES_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT, "VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_DISJOINT_BIT, "VK_FORMAT_FEATURE_DISJOINT_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_DISJOINT_BIT_KHR, "VK_FORMAT_FEATURE_DISJOINT_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_FRAGMENT_DENSITY_MAP_BIT_EXT, "VK_FORMAT_FEATURE_FRAGMENT_DENSITY_MAP_BIT_EXT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT, "VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR, "VK_FORMAT_FEATURE_MIDPOINT_CHROMA_SAMPLES_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_RESERVED_25_BIT_KHR, "VK_FORMAT_FEATURE_RESERVED_25_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_RESERVED_26_BIT_KHR, "VK_FORMAT_FEATURE_RESERVED_26_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_RESERVED_27_BIT_KHR, "VK_FORMAT_FEATURE_RESERVED_27_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_RESERVED_28_BIT_KHR, "VK_FORMAT_FEATURE_RESERVED_28_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_LINEAR_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR, "VK_FORMAT_FEATURE_SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT, "VK_FORMAT_FEATURE_STORAGE_IMAGE_ATOMIC_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT, "VK_FORMAT_FEATURE_STORAGE_IMAGE_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT, "VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_ATOMIC_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT, "VK_FORMAT_FEATURE_STORAGE_TEXEL_BUFFER_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_TRANSFER_DST_BIT, "VK_FORMAT_FEATURE_TRANSFER_DST_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR, "VK_FORMAT_FEATURE_TRANSFER_DST_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_TRANSFER_SRC_BIT, "VK_FORMAT_FEATURE_TRANSFER_SRC_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR, "VK_FORMAT_FEATURE_TRANSFER_SRC_BIT_KHR" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT, "VK_FORMAT_FEATURE_UNIFORM_TEXEL_BUFFER_BIT" },
    { VkFormatFeatureFlagBits::VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT, "VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT" },
    { VkFormatFeatureFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkFramebufferCreateFlagBits, std::string> Meta_StringsByVkFramebufferCreateFlagBits =
{
    { VkFramebufferCreateFlagBits::VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT_KHR, "VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT_KHR" },
    { VkFramebufferCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkGeometryFlagBitsNV, std::string> Meta_StringsByVkGeometryFlagBitsNV =
{
    { VkGeometryFlagBitsNV::VK_GEOMETRY_NO_DUPLICATE_ANY_HIT_INVOCATION_BIT_NV, "VK_GEOMETRY_NO_DUPLICATE_ANY_HIT_INVOCATION_BIT_NV" },
    { VkGeometryFlagBitsNV::VK_GEOMETRY_OPAQUE_BIT_NV, "VK_GEOMETRY_OPAQUE_BIT_NV" },
    { VkGeometryFlagBitsNV::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkGeometryInstanceFlagBitsNV, std::string> Meta_StringsByVkGeometryInstanceFlagBitsNV =
{
    { VkGeometryInstanceFlagBitsNV::VK_GEOMETRY_INSTANCE_FORCE_NO_OPAQUE_BIT_NV, "VK_GEOMETRY_INSTANCE_FORCE_NO_OPAQUE_BIT_NV" },
    { VkGeometryInstanceFlagBitsNV::VK_GEOMETRY_INSTANCE_FORCE_OPAQUE_BIT_NV, "VK_GEOMETRY_INSTANCE_FORCE_OPAQUE_BIT_NV" },
    { VkGeometryInstanceFlagBitsNV::VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV, "VK_GEOMETRY_INSTANCE_TRIANGLE_CULL_DISABLE_BIT_NV" },
    { VkGeometryInstanceFlagBitsNV::VK_GEOMETRY_INSTANCE_TRIANGLE_FRONT_COUNTERCLOCKWISE_BIT_NV, "VK_GEOMETRY_INSTANCE_TRIANGLE_FRONT_COUNTERCLOCKWISE_BIT_NV" },
    { VkGeometryInstanceFlagBitsNV::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkImageAspectFlagBits, std::string> Meta_StringsByVkImageAspectFlagBits =
{
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_COLOR_BIT, "VK_IMAGE_ASPECT_COLOR_BIT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_DEPTH_BIT, "VK_IMAGE_ASPECT_DEPTH_BIT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT, "VK_IMAGE_ASPECT_MEMORY_PLANE_0_BIT_EXT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_MEMORY_PLANE_1_BIT_EXT, "VK_IMAGE_ASPECT_MEMORY_PLANE_1_BIT_EXT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT, "VK_IMAGE_ASPECT_MEMORY_PLANE_2_BIT_EXT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_MEMORY_PLANE_3_BIT_EXT, "VK_IMAGE_ASPECT_MEMORY_PLANE_3_BIT_EXT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_METADATA_BIT, "VK_IMAGE_ASPECT_METADATA_BIT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_0_BIT, "VK_IMAGE_ASPECT_PLANE_0_BIT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_0_BIT_KHR, "VK_IMAGE_ASPECT_PLANE_0_BIT_KHR" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_1_BIT, "VK_IMAGE_ASPECT_PLANE_1_BIT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_1_BIT_KHR, "VK_IMAGE_ASPECT_PLANE_1_BIT_KHR" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_2_BIT, "VK_IMAGE_ASPECT_PLANE_2_BIT" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_PLANE_2_BIT_KHR, "VK_IMAGE_ASPECT_PLANE_2_BIT_KHR" },
    { VkImageAspectFlagBits::VK_IMAGE_ASPECT_STENCIL_BIT, "VK_IMAGE_ASPECT_STENCIL_BIT" },
    { VkImageAspectFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkImageCreateFlagBits, std::string> Meta_StringsByVkImageCreateFlagBits =
{
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT, "VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR, "VK_IMAGE_CREATE_2D_ARRAY_COMPATIBLE_BIT_KHR" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_ALIAS_BIT, "VK_IMAGE_CREATE_ALIAS_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_ALIAS_BIT_KHR, "VK_IMAGE_CREATE_ALIAS_BIT_KHR" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT, "VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR, "VK_IMAGE_CREATE_BLOCK_TEXEL_VIEW_COMPATIBLE_BIT_KHR" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_CORNER_SAMPLED_BIT_NV, "VK_IMAGE_CREATE_CORNER_SAMPLED_BIT_NV" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT, "VK_IMAGE_CREATE_CUBE_COMPATIBLE_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_DISJOINT_BIT, "VK_IMAGE_CREATE_DISJOINT_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_DISJOINT_BIT_KHR, "VK_IMAGE_CREATE_DISJOINT_BIT_KHR" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_EXTENDED_USAGE_BIT, "VK_IMAGE_CREATE_EXTENDED_USAGE_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_EXTENDED_USAGE_BIT_KHR, "VK_IMAGE_CREATE_EXTENDED_USAGE_BIT_KHR" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT, "VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_PROTECTED_BIT, "VK_IMAGE_CREATE_PROTECTED_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT, "VK_IMAGE_CREATE_SAMPLE_LOCATIONS_COMPATIBLE_DEPTH_BIT_EXT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_SPARSE_ALIASED_BIT, "VK_IMAGE_CREATE_SPARSE_ALIASED_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_SPARSE_BINDING_BIT, "VK_IMAGE_CREATE_SPARSE_BINDING_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT, "VK_IMAGE_CREATE_SPARSE_RESIDENCY_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT, "VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR, "VK_IMAGE_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR" },
    { VkImageCreateFlagBits::VK_IMAGE_CREATE_SUBSAMPLED_BIT_EXT, "VK_IMAGE_CREATE_SUBSAMPLED_BIT_EXT" },
    { VkImageCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkImageUsageFlagBits, std::string> Meta_StringsByVkImageUsageFlagBits =
{
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT, "VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT, "VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT, "VK_IMAGE_USAGE_FRAGMENT_DENSITY_MAP_BIT_EXT" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT, "VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_10_BIT_KHR, "VK_IMAGE_USAGE_RESERVED_10_BIT_KHR" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_11_BIT_KHR, "VK_IMAGE_USAGE_RESERVED_11_BIT_KHR" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_12_BIT_KHR, "VK_IMAGE_USAGE_RESERVED_12_BIT_KHR" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_13_BIT_KHR, "VK_IMAGE_USAGE_RESERVED_13_BIT_KHR" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_14_BIT_KHR, "VK_IMAGE_USAGE_RESERVED_14_BIT_KHR" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_RESERVED_15_BIT_KHR, "VK_IMAGE_USAGE_RESERVED_15_BIT_KHR" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_SAMPLED_BIT, "VK_IMAGE_USAGE_SAMPLED_BIT" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV, "VK_IMAGE_USAGE_SHADING_RATE_IMAGE_BIT_NV" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_STORAGE_BIT, "VK_IMAGE_USAGE_STORAGE_BIT" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_TRANSFER_DST_BIT, "VK_IMAGE_USAGE_TRANSFER_DST_BIT" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_TRANSFER_SRC_BIT, "VK_IMAGE_USAGE_TRANSFER_SRC_BIT" },
    { VkImageUsageFlagBits::VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT, "VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT" },
    { VkImageUsageFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkImageViewCreateFlagBits, std::string> Meta_StringsByVkImageViewCreateFlagBits =
{
    { VkImageViewCreateFlagBits::VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT, "VK_IMAGE_VIEW_CREATE_FRAGMENT_DENSITY_MAP_DYNAMIC_BIT_EXT" },
    { VkImageViewCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkIndirectCommandsLayoutUsageFlagBitsNVX, std::string> Meta_StringsByVkIndirectCommandsLayoutUsageFlagBitsNVX =
{
    { VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EMPTY_EXECUTIONS_BIT_NVX, "VK_INDIRECT_COMMANDS_LAYOUT_USAGE_EMPTY_EXECUTIONS_BIT_NVX" },
    { VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NVX, "VK_INDIRECT_COMMANDS_LAYOUT_USAGE_INDEXED_SEQUENCES_BIT_NVX" },
    { VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_INDIRECT_COMMANDS_LAYOUT_USAGE_SPARSE_SEQUENCES_BIT_NVX, "VK_INDIRECT_COMMANDS_LAYOUT_USAGE_SPARSE_SEQUENCES_BIT_NVX" },
    { VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NVX, "VK_INDIRECT_COMMANDS_LAYOUT_USAGE_UNORDERED_SEQUENCES_BIT_NVX" },
    { VkIndirectCommandsLayoutUsageFlagBitsNVX::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkInstanceCreateFlagBits, std::string> Meta_StringsByVkInstanceCreateFlagBits =
{
    { VkInstanceCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkMemoryAllocateFlagBits, std::string> Meta_StringsByVkMemoryAllocateFlagBits =
{
    { VkMemoryAllocateFlagBits::VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT, "VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT" },
    { VkMemoryAllocateFlagBits::VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT_KHR, "VK_MEMORY_ALLOCATE_DEVICE_MASK_BIT_KHR" },
    { VkMemoryAllocateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkMemoryAllocateFlagBitsKHR, std::string> Meta_StringsByVkMemoryAllocateFlagBitsKHR =
{
    { VkMemoryAllocateFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkMemoryHeapFlagBits, std::string> Meta_StringsByVkMemoryHeapFlagBits =
{
    { VkMemoryHeapFlagBits::VK_MEMORY_HEAP_DEVICE_LOCAL_BIT, "VK_MEMORY_HEAP_DEVICE_LOCAL_BIT" },
    { VkMemoryHeapFlagBits::VK_MEMORY_HEAP_MULTI_INSTANCE_BIT, "VK_MEMORY_HEAP_MULTI_INSTANCE_BIT" },
    { VkMemoryHeapFlagBits::VK_MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR, "VK_MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR" },
    { VkMemoryHeapFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkMemoryPropertyFlagBits, std::string> Meta_StringsByVkMemoryPropertyFlagBits =
{
    { VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, "VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT" },
    { VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_HOST_CACHED_BIT, "VK_MEMORY_PROPERTY_HOST_CACHED_BIT" },
    { VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_HOST_COHERENT_BIT, "VK_MEMORY_PROPERTY_HOST_COHERENT_BIT" },
    { VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT, "VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT" },
    { VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT, "VK_MEMORY_PROPERTY_LAZILY_ALLOCATED_BIT" },
    { VkMemoryPropertyFlagBits::VK_MEMORY_PROPERTY_PROTECTED_BIT, "VK_MEMORY_PROPERTY_PROTECTED_BIT" },
    { VkMemoryPropertyFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkObjectEntryUsageFlagBitsNVX, std::string> Meta_StringsByVkObjectEntryUsageFlagBitsNVX =
{
    { VkObjectEntryUsageFlagBitsNVX::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkObjectEntryUsageFlagBitsNVX::VK_OBJECT_ENTRY_USAGE_COMPUTE_BIT_NVX, "VK_OBJECT_ENTRY_USAGE_COMPUTE_BIT_NVX" },
    { VkObjectEntryUsageFlagBitsNVX::VK_OBJECT_ENTRY_USAGE_GRAPHICS_BIT_NVX, "VK_OBJECT_ENTRY_USAGE_GRAPHICS_BIT_NVX" }
};

const std::unordered_map<VkPeerMemoryFeatureFlagBits, std::string> Meta_StringsByVkPeerMemoryFeatureFlagBits =
{
    { VkPeerMemoryFeatureFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_COPY_DST_BIT, "VK_PEER_MEMORY_FEATURE_COPY_DST_BIT" },
    { VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_COPY_DST_BIT_KHR, "VK_PEER_MEMORY_FEATURE_COPY_DST_BIT_KHR" },
    { VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT, "VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT" },
    { VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT_KHR, "VK_PEER_MEMORY_FEATURE_COPY_SRC_BIT_KHR" },
    { VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT, "VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT" },
    { VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT_KHR, "VK_PEER_MEMORY_FEATURE_GENERIC_DST_BIT_KHR" },
    { VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT, "VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT" },
    { VkPeerMemoryFeatureFlagBits::VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT_KHR, "VK_PEER_MEMORY_FEATURE_GENERIC_SRC_BIT_KHR" }
};

const std::unordered_map<VkPeerMemoryFeatureFlagBitsKHR, std::string> Meta_StringsByVkPeerMemoryFeatureFlagBitsKHR =
{
    { VkPeerMemoryFeatureFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineCacheCreateFlagBits, std::string> Meta_StringsByVkPipelineCacheCreateFlagBits =
{
    { VkPipelineCacheCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineColorBlendStateCreateFlagBits, std::string> Meta_StringsByVkPipelineColorBlendStateCreateFlagBits =
{
    { VkPipelineColorBlendStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineCreateFlagBits, std::string> Meta_StringsByVkPipelineCreateFlagBits =
{
    { VkPipelineCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT, "VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT" },
    { VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV, "VK_PIPELINE_CREATE_DEFER_COMPILE_BIT_NV" },
    { VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DERIVATIVE_BIT, "VK_PIPELINE_CREATE_DERIVATIVE_BIT" },
    { VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT, "VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT" },
    { VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DISPATCH_BASE, "VK_PIPELINE_CREATE_DISPATCH_BASE" },
    { VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_DISPATCH_BASE_KHR, "VK_PIPELINE_CREATE_DISPATCH_BASE_KHR" },
    { VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT, "VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT" },
    { VkPipelineCreateFlagBits::VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR, "VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR" }
};

const std::unordered_map<VkPipelineCreationFeedbackFlagBitsEXT, std::string> Meta_StringsByVkPipelineCreationFeedbackFlagBitsEXT =
{
    { VkPipelineCreationFeedbackFlagBitsEXT::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkPipelineCreationFeedbackFlagBitsEXT::VK_PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT_EXT, "VK_PIPELINE_CREATION_FEEDBACK_APPLICATION_PIPELINE_CACHE_HIT_BIT_EXT" },
    { VkPipelineCreationFeedbackFlagBitsEXT::VK_PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT_EXT, "VK_PIPELINE_CREATION_FEEDBACK_BASE_PIPELINE_ACCELERATION_BIT_EXT" },
    { VkPipelineCreationFeedbackFlagBitsEXT::VK_PIPELINE_CREATION_FEEDBACK_VALID_BIT_EXT, "VK_PIPELINE_CREATION_FEEDBACK_VALID_BIT_EXT" }
};

const std::unordered_map<VkPipelineDepthStencilStateCreateFlagBits, std::string> Meta_StringsByVkPipelineDepthStencilStateCreateFlagBits =
{
    { VkPipelineDepthStencilStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineDynamicStateCreateFlagBits, std::string> Meta_StringsByVkPipelineDynamicStateCreateFlagBits =
{
    { VkPipelineDynamicStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineInputAssemblyStateCreateFlagBits, std::string> Meta_StringsByVkPipelineInputAssemblyStateCreateFlagBits =
{
    { VkPipelineInputAssemblyStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineLayoutCreateFlagBits, std::string> Meta_StringsByVkPipelineLayoutCreateFlagBits =
{
    { VkPipelineLayoutCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineMultisampleStateCreateFlagBits, std::string> Meta_StringsByVkPipelineMultisampleStateCreateFlagBits =
{
    { VkPipelineMultisampleStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineRasterizationStateCreateFlagBits, std::string> Meta_StringsByVkPipelineRasterizationStateCreateFlagBits =
{
    { VkPipelineRasterizationStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineShaderStageCreateFlagBits, std::string> Meta_StringsByVkPipelineShaderStageCreateFlagBits =
{
    { VkPipelineShaderStageCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkPipelineShaderStageCreateFlagBits::VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT, "VK_PIPELINE_SHADER_STAGE_CREATE_ALLOW_VARYING_SUBGROUP_SIZE_BIT_EXT" },
    { VkPipelineShaderStageCreateFlagBits::VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT, "VK_PIPELINE_SHADER_STAGE_CREATE_REQUIRE_FULL_SUBGROUPS_BIT_EXT" },
    { VkPipelineShaderStageCreateFlagBits::VK_PIPELINE_SHADER_STAGE_CREATE_RESERVED_2_BIT_NV, "VK_PIPELINE_SHADER_STAGE_CREATE_RESERVED_2_BIT_NV" }
};

const std::unordered_map<VkPipelineStageFlagBits, std::string> Meta_StringsByVkPipelineStageFlagBits =
{
    { VkPipelineStageFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV, "VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_NV" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_ALL_COMMANDS_BIT, "VK_PIPELINE_STAGE_ALL_COMMANDS_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT, "VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, "VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT, "VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX, "VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, "VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT, "VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT, "VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT, "VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT, "VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT, "VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT, "VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_HOST_BIT, "VK_PIPELINE_STAGE_HOST_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT, "VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV, "VK_PIPELINE_STAGE_MESH_SHADER_BIT_NV" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV, "VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_RESERVED_26_BIT_KHR, "VK_PIPELINE_STAGE_RESERVED_26_BIT_KHR" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_RESERVED_27_BIT_KHR, "VK_PIPELINE_STAGE_RESERVED_27_BIT_KHR" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV, "VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV, "VK_PIPELINE_STAGE_TASK_SHADER_BIT_NV" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT, "VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT, "VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT, "VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TRANSFER_BIT, "VK_PIPELINE_STAGE_TRANSFER_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT, "VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_VERTEX_INPUT_BIT, "VK_PIPELINE_STAGE_VERTEX_INPUT_BIT" },
    { VkPipelineStageFlagBits::VK_PIPELINE_STAGE_VERTEX_SHADER_BIT, "VK_PIPELINE_STAGE_VERTEX_SHADER_BIT" }
};

const std::unordered_map<VkPipelineTessellationStateCreateFlagBits, std::string> Meta_StringsByVkPipelineTessellationStateCreateFlagBits =
{
    { VkPipelineTessellationStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineVertexInputStateCreateFlagBits, std::string> Meta_StringsByVkPipelineVertexInputStateCreateFlagBits =
{
    { VkPipelineVertexInputStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkPipelineViewportStateCreateFlagBits, std::string> Meta_StringsByVkPipelineViewportStateCreateFlagBits =
{
    { VkPipelineViewportStateCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkQueryControlFlagBits, std::string> Meta_StringsByVkQueryControlFlagBits =
{
    { VkQueryControlFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkQueryControlFlagBits::VK_QUERY_CONTROL_PRECISE_BIT, "VK_QUERY_CONTROL_PRECISE_BIT" }
};

const std::unordered_map<VkQueryPipelineStatisticFlagBits, std::string> Meta_StringsByVkQueryPipelineStatisticFlagBits =
{
    { VkQueryPipelineStatisticFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT, "VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT, "VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT, "VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT, "VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT, "VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT, "VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT, "VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT, "VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT, "VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT, "VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT" },
    { VkQueryPipelineStatisticFlagBits::VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT, "VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT" }
};

const std::unordered_map<VkQueryPoolCreateFlagBits, std::string> Meta_StringsByVkQueryPoolCreateFlagBits =
{
    { VkQueryPoolCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkQueryResultFlagBits, std::string> Meta_StringsByVkQueryResultFlagBits =
{
    { VkQueryResultFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkQueryResultFlagBits::VK_QUERY_RESULT_64_BIT, "VK_QUERY_RESULT_64_BIT" },
    { VkQueryResultFlagBits::VK_QUERY_RESULT_PARTIAL_BIT, "VK_QUERY_RESULT_PARTIAL_BIT" },
    { VkQueryResultFlagBits::VK_QUERY_RESULT_WAIT_BIT, "VK_QUERY_RESULT_WAIT_BIT" },
    { VkQueryResultFlagBits::VK_QUERY_RESULT_WITH_AVAILABILITY_BIT, "VK_QUERY_RESULT_WITH_AVAILABILITY_BIT" }
};

const std::unordered_map<VkQueueFlagBits, std::string> Meta_StringsByVkQueueFlagBits =
{
    { VkQueueFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkQueueFlagBits::VK_QUEUE_COMPUTE_BIT, "VK_QUEUE_COMPUTE_BIT" },
    { VkQueueFlagBits::VK_QUEUE_GRAPHICS_BIT, "VK_QUEUE_GRAPHICS_BIT" },
    { VkQueueFlagBits::VK_QUEUE_PROTECTED_BIT, "VK_QUEUE_PROTECTED_BIT" },
    { VkQueueFlagBits::VK_QUEUE_RESERVED_5_BIT_KHR, "VK_QUEUE_RESERVED_5_BIT_KHR" },
    { VkQueueFlagBits::VK_QUEUE_RESERVED_6_BIT_KHR, "VK_QUEUE_RESERVED_6_BIT_KHR" },
    { VkQueueFlagBits::VK_QUEUE_SPARSE_BINDING_BIT, "VK_QUEUE_SPARSE_BINDING_BIT" },
    { VkQueueFlagBits::VK_QUEUE_TRANSFER_BIT, "VK_QUEUE_TRANSFER_BIT" }
};

const std::unordered_map<VkRenderPassCreateFlagBits, std::string> Meta_StringsByVkRenderPassCreateFlagBits =
{
    { VkRenderPassCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkRenderPassCreateFlagBits::VK_RENDER_PASS_CREATE_RESERVED_0_BIT_KHR, "VK_RENDER_PASS_CREATE_RESERVED_0_BIT_KHR" },
    { VkRenderPassCreateFlagBits::VK_RENDER_PASS_RESERVED_BIT_1_QCOM, "VK_RENDER_PASS_RESERVED_BIT_1_QCOM" }
};

const std::unordered_map<VkResolveModeFlagBitsKHR, std::string> Meta_StringsByVkResolveModeFlagBitsKHR =
{
    { VkResolveModeFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_AVERAGE_BIT_KHR, "VK_RESOLVE_MODE_AVERAGE_BIT_KHR" },
    { VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_MAX_BIT_KHR, "VK_RESOLVE_MODE_MAX_BIT_KHR" },
    { VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_MIN_BIT_KHR, "VK_RESOLVE_MODE_MIN_BIT_KHR" },
    { VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_NONE_KHR, "VK_RESOLVE_MODE_NONE_KHR" },
    { VkResolveModeFlagBitsKHR::VK_RESOLVE_MODE_SAMPLE_ZERO_BIT_KHR, "VK_RESOLVE_MODE_SAMPLE_ZERO_BIT_KHR" }
};

const std::unordered_map<VkSampleCountFlagBits, std::string> Meta_StringsByVkSampleCountFlagBits =
{
    { VkSampleCountFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSampleCountFlagBits::VK_SAMPLE_COUNT_16_BIT, "VK_SAMPLE_COUNT_16_BIT" },
    { VkSampleCountFlagBits::VK_SAMPLE_COUNT_1_BIT, "VK_SAMPLE_COUNT_1_BIT" },
    { VkSampleCountFlagBits::VK_SAMPLE_COUNT_2_BIT, "VK_SAMPLE_COUNT_2_BIT" },
    { VkSampleCountFlagBits::VK_SAMPLE_COUNT_32_BIT, "VK_SAMPLE_COUNT_32_BIT" },
    { VkSampleCountFlagBits::VK_SAMPLE_COUNT_4_BIT, "VK_SAMPLE_COUNT_4_BIT" },
    { VkSampleCountFlagBits::VK_SAMPLE_COUNT_64_BIT, "VK_SAMPLE_COUNT_64_BIT" },
    { VkSampleCountFlagBits::VK_SAMPLE_COUNT_8_BIT, "VK_SAMPLE_COUNT_8_BIT" }
};

const std::unordered_map<VkSamplerCreateFlagBits, std::string> Meta_StringsByVkSamplerCreateFlagBits =
{
    { VkSamplerCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSamplerCreateFlagBits::VK_SAMPLER_CREATE_SUBSAMPLED_BIT_EXT, "VK_SAMPLER_CREATE_SUBSAMPLED_BIT_EXT" },
    { VkSamplerCreateFlagBits::VK_SAMPLER_CREATE_SUBSAMPLED_COARSE_RECONSTRUCTION_BIT_EXT, "VK_SAMPLER_CREATE_SUBSAMPLED_COARSE_RECONSTRUCTION_BIT_EXT" }
};

const std::unordered_map<VkSemaphoreImportFlagBits, std::string> Meta_StringsByVkSemaphoreImportFlagBits =
{
    { VkSemaphoreImportFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSemaphoreImportFlagBits::VK_SEMAPHORE_IMPORT_TEMPORARY_BIT, "VK_SEMAPHORE_IMPORT_TEMPORARY_BIT" },
    { VkSemaphoreImportFlagBits::VK_SEMAPHORE_IMPORT_TEMPORARY_BIT_KHR, "VK_SEMAPHORE_IMPORT_TEMPORARY_BIT_KHR" }
};

const std::unordered_map<VkSemaphoreImportFlagBitsKHR, std::string> Meta_StringsByVkSemaphoreImportFlagBitsKHR =
{
    { VkSemaphoreImportFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" }
};

const std::unordered_map<VkShaderModuleCreateFlagBits, std::string> Meta_StringsByVkShaderModuleCreateFlagBits =
{
    { VkShaderModuleCreateFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkShaderModuleCreateFlagBits::VK_SHADER_MODULE_CREATE_RESERVED_0_BIT_NV, "VK_SHADER_MODULE_CREATE_RESERVED_0_BIT_NV" }
};

const std::unordered_map<VkShaderStageFlagBits, std::string> Meta_StringsByVkShaderStageFlagBits =
{
    { VkShaderStageFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_ALL, "VK_SHADER_STAGE_ALL" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_ALL_GRAPHICS, "VK_SHADER_STAGE_ALL_GRAPHICS" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_ANY_HIT_BIT_NV, "VK_SHADER_STAGE_ANY_HIT_BIT_NV" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_CALLABLE_BIT_NV, "VK_SHADER_STAGE_CALLABLE_BIT_NV" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV, "VK_SHADER_STAGE_CLOSEST_HIT_BIT_NV" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_COMPUTE_BIT, "VK_SHADER_STAGE_COMPUTE_BIT" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_FRAGMENT_BIT, "VK_SHADER_STAGE_FRAGMENT_BIT" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_GEOMETRY_BIT, "VK_SHADER_STAGE_GEOMETRY_BIT" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_INTERSECTION_BIT_NV, "VK_SHADER_STAGE_INTERSECTION_BIT_NV" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_MESH_BIT_NV, "VK_SHADER_STAGE_MESH_BIT_NV" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_MISS_BIT_NV, "VK_SHADER_STAGE_MISS_BIT_NV" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_RAYGEN_BIT_NV, "VK_SHADER_STAGE_RAYGEN_BIT_NV" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_TASK_BIT_NV, "VK_SHADER_STAGE_TASK_BIT_NV" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT, "VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT, "VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT" },
    { VkShaderStageFlagBits::VK_SHADER_STAGE_VERTEX_BIT, "VK_SHADER_STAGE_VERTEX_BIT" }
};

const std::unordered_map<VkSparseImageFormatFlagBits, std::string> Meta_StringsByVkSparseImageFormatFlagBits =
{
    { VkSparseImageFormatFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSparseImageFormatFlagBits::VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT, "VK_SPARSE_IMAGE_FORMAT_ALIGNED_MIP_SIZE_BIT" },
    { VkSparseImageFormatFlagBits::VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT, "VK_SPARSE_IMAGE_FORMAT_NONSTANDARD_BLOCK_SIZE_BIT" },
    { VkSparseImageFormatFlagBits::VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT, "VK_SPARSE_IMAGE_FORMAT_SINGLE_MIPTAIL_BIT" }
};

const std::unordered_map<VkSparseMemoryBindFlagBits, std::string> Meta_StringsByVkSparseMemoryBindFlagBits =
{
    { VkSparseMemoryBindFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSparseMemoryBindFlagBits::VK_SPARSE_MEMORY_BIND_METADATA_BIT, "VK_SPARSE_MEMORY_BIND_METADATA_BIT" }
};

const std::unordered_map<VkStencilFaceFlagBits, std::string> Meta_StringsByVkStencilFaceFlagBits =
{
    { VkStencilFaceFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkStencilFaceFlagBits::VK_STENCIL_FACE_BACK_BIT, "VK_STENCIL_FACE_BACK_BIT" },
    { VkStencilFaceFlagBits::VK_STENCIL_FACE_FRONT_AND_BACK, "VK_STENCIL_FACE_FRONT_AND_BACK" },
    { VkStencilFaceFlagBits::VK_STENCIL_FACE_FRONT_BIT, "VK_STENCIL_FACE_FRONT_BIT" },
    { VkStencilFaceFlagBits::VK_STENCIL_FRONT_AND_BACK, "VK_STENCIL_FRONT_AND_BACK" }
};

const std::unordered_map<VkSubgroupFeatureFlagBits, std::string> Meta_StringsByVkSubgroupFeatureFlagBits =
{
    { VkSubgroupFeatureFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_ARITHMETIC_BIT, "VK_SUBGROUP_FEATURE_ARITHMETIC_BIT" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_BALLOT_BIT, "VK_SUBGROUP_FEATURE_BALLOT_BIT" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_BASIC_BIT, "VK_SUBGROUP_FEATURE_BASIC_BIT" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_CLUSTERED_BIT, "VK_SUBGROUP_FEATURE_CLUSTERED_BIT" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_PARTITIONED_BIT_NV, "VK_SUBGROUP_FEATURE_PARTITIONED_BIT_NV" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_QUAD_BIT, "VK_SUBGROUP_FEATURE_QUAD_BIT" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_SHUFFLE_BIT, "VK_SUBGROUP_FEATURE_SHUFFLE_BIT" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT, "VK_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT" },
    { VkSubgroupFeatureFlagBits::VK_SUBGROUP_FEATURE_VOTE_BIT, "VK_SUBGROUP_FEATURE_VOTE_BIT" }
};

const std::unordered_map<VkSubpassDescriptionFlagBits, std::string> Meta_StringsByVkSubpassDescriptionFlagBits =
{
    { VkSubpassDescriptionFlagBits::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSubpassDescriptionFlagBits::VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX, "VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX" },
    { VkSubpassDescriptionFlagBits::VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX, "VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX" },
    { VkSubpassDescriptionFlagBits::VK_SUBPASS_DESCRIPTION_RESERVED_2_BIT_QCOM, "VK_SUBPASS_DESCRIPTION_RESERVED_2_BIT_QCOM" },
    { VkSubpassDescriptionFlagBits::VK_SUBPASS_DESCRIPTION_RESERVED_3_BIT_QCOM, "VK_SUBPASS_DESCRIPTION_RESERVED_3_BIT_QCOM" }
};

const std::unordered_map<VkSurfaceCounterFlagBitsEXT, std::string> Meta_StringsByVkSurfaceCounterFlagBitsEXT =
{
    { VkSurfaceCounterFlagBitsEXT::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSurfaceCounterFlagBitsEXT::VK_SURFACE_COUNTER_VBLANK_EXT, "VK_SURFACE_COUNTER_VBLANK_EXT" }
};

const std::unordered_map<VkSurfaceTransformFlagBitsKHR, std::string> Meta_StringsByVkSurfaceTransformFlagBitsKHR =
{
    { VkSurfaceTransformFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR, "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR, "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR, "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR, "VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR, "VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR, "VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR, "VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR, "VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR" },
    { VkSurfaceTransformFlagBitsKHR::VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR, "VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR" }
};

const std::unordered_map<VkSwapchainCreateFlagBitsKHR, std::string> Meta_StringsByVkSwapchainCreateFlagBitsKHR =
{
    { VkSwapchainCreateFlagBitsKHR::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSwapchainCreateFlagBitsKHR::VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR, "VK_SWAPCHAIN_CREATE_MUTABLE_FORMAT_BIT_KHR" },
    { VkSwapchainCreateFlagBitsKHR::VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR, "VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR" },
    { VkSwapchainCreateFlagBitsKHR::VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR, "VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR" }
};

const std::unordered_map<VkSwapchainImageUsageFlagBitsANDROID, std::string> Meta_StringsByVkSwapchainImageUsageFlagBitsANDROID =
{
    { VkSwapchainImageUsageFlagBitsANDROID::VK_NONE_BIT, "VK_NONE_BIT" },
    { VkSwapchainImageUsageFlagBitsANDROID::VK_SWAPCHAIN_IMAGE_USAGE_SHARED_BIT_ANDROID, "VK_SWAPCHAIN_IMAGE_USAGE_SHARED_BIT_ANDROID" }
};


} } // namespace vkbinding::aux